/**
 * DynamoDB key builders and access helpers for the product table.
 */

export { getDocClient, resetDocClient } from './client.js';
export {
  decodeCursor,
  deleteItem,
  encodeCursor,
  getItem,
  putItem,
  queryAll,
  queryBySkBetween,
  queryBySkPrefix,
  queryPage,
  queryPartition,
  transactWrite,
} from './access.js';export {
  CHAT_MEMBER_SK_PREFIX,
  CONNECTION_SK_PREFIX,
  CONNECTION_TTL_SECONDS,
  DEVICE_SK_PREFIX,
  EVENT_SK_PREFIX,
  GSI_CONNECTION_ID,
  GSI_EMAIL,
  JOIN_REQUEST_SK_PREFIX,
  MESSAGE_SK_PREFIX,
  ROLE_PERMISSIONS_SK_PREFIX,
  RSVP_SK_PREFIX,
  TABLE_PK,
  TABLE_SK,
  TEAM_INVITE_SK_PREFIX,
  TEAM_MEMBER_SK_PREFIX,
  USER_CHAT_SK_PREFIX,
  USER_TEAM_SK_PREFIX,
  chatMemberSk,
  chatMetaSk,
  chatPk,
  connectionSk,
  deviceSk,
  eventSk,
  inviteMetaSk,
  invitePk,
  joinRequestSk,
  messageSk,
  profileSk,
  rolePermissionsSk,
  rsvpSk,
  rsvpSkLegacy,
  rsvpSkRange,
  teamInviteSk,
  teamMemberSk,
  teamMetaSk,
  teamPk,
  teamDirectoryPk,
  teamDirectorySk,
  teamDirectorySkPrefix,
  userChatSk,
  userPk,
  userTeamSk,
  type ChatId,
  type InviteCode,
  type TeamId,
  type UserId,
} from './keys.js';
