/**
 * Shared Zod schemas for the GamePlan product API.
 */

export { z, type ZodType } from './zod.js';
export { MAX_UPLOAD_BYTES } from './limits.js';
export { openApiDocument } from './openapi.js';
export {
  DEFAULT_ROLE_PERMISSIONS,
  TEAM_PERMISSIONS,
  TEAM_ROLES,
} from './constants.js';

export {
  ACCOUNT_KINDS,
  CHAT_KINDS,
  DEVICE_PLATFORMS,
  EVENT_TYPES,
  RSVP_STATUSES,
  accountKindSchema,
  chatKindSchema,
  devicePlatformSchema,
  eventTypeSchema,
  rsvpStatusSchema,
  teamPermissionSchema,
  teamRoleSchema,
  type AccountKind,
  type ChatKind,
  type DevicePlatform,
  type EventType,
  type RsvpStatus,
  type TeamPermission,
  type TeamRole,
} from './enums.js';

export {
  authUserSchema,
  completeProfileBodySchema,
  errorBodySchema,
  loginBodySchema,
  refreshBodySchema,
  registerBodySchema,
  sessionTokensSchema,
  updateProfileBodySchema,
  userProfileSchema,
  type AuthUser,
  type CompleteProfileBody,
  type ErrorBody,
  type LoginBody,
  type RefreshBody,
  type RegisterBody,
  type SessionTokens,
  type UpdateProfileBody,
  type UserProfile,
} from './auth.js';

export {
  acceptedInviteSchema,
  approveJoinRequestBodySchema,
  assignRoleBodySchema,
  createInviteBodySchema,
  createTeamBodySchema,
  invitePreviewSchema,
  approvedJoinRequestSchema,
  joinRequestCreatedSchema,
  joinRequestListSchema,
  joinRequestSchema,
  rolePermissionsResponseSchema,
  rolePermissionsSchema,
  searchTeamDirectoryQuerySchema,
  teamDirectoryHitSchema,
  teamDirectoryPageSchema,
  teamInviteListSchema,
  teamInviteSchema,
  teamListSchema,
  teamMemberListSchema,
  teamMemberSchema,
  teamSummarySchema,
  teamThemeSchema,
  updatePositionsBodySchema,
  updateRolePermissionsBodySchema,
  updateTeamBodySchema,
  type AcceptedInvite,
  type ApproveJoinRequestBody,
  type AssignRoleBody,
  type CreateInviteBody,
  type CreateTeamBody,
  type InvitePreview,
  type ApprovedJoinRequest,
  type JoinRequest,
  type JoinRequestCreated,
  type JoinRequestList,
  type RolePermissions,
  type RolePermissionsResponse,
  type SearchTeamDirectoryQuery,
  type TeamDirectoryHit,
  type TeamDirectoryPage,
  type TeamInvite,
  type TeamInviteList,
  type TeamList,
  type TeamMember,
  type TeamMemberList,
  type TeamSummary,
  type TeamTheme,
  type UpdatePositionsBody,
  type UpdateRolePermissionsBody,
  type UpdateTeamBody,
} from './teams.js';

export {
  createEventBodySchema,
  eventResponseSchema,
  recurrenceRuleSchema,
  rsvpBodySchema,
  rsvpResponseSchema,
  scheduleListSchema,
  scheduleOccurrenceSchema,
  scheduleWindowQuerySchema,
  updateEventBodySchema,
  type CreateEventBody,
  type EventResponse,
  type RecurrenceRule,
  type RsvpBody,
  type RsvpResponse,
  type ScheduleList,
  type ScheduleOccurrence,
  type ScheduleWindowQuery,
  type UpdateEventBody,
} from './schedule.js';

export {
  chatListSchema,
  chatMessageSchema,
  chatSummarySchema,
  createPrivateChatBodySchema,
  createTeamChannelBodySchema,
  messageHistoryQuerySchema,
  messagePageSchema,
  searchUsersQuerySchema,
  sendMessageBodySchema,
  type ChatList,
  type ChatMessage,
  type ChatSummary,
  type CreatePrivateChatBody,
  type CreateTeamChannelBody,
  type MessageHistoryQuery,
  type MessagePage,
  type SearchUsersQuery,
  type SendMessageBody,
} from './chat.js';

export {
  deviceRegistrationSchema,
  presignDownloadQuerySchema,
  presignDownloadResponseSchema,
  registerDeviceBodySchema,
  presignUploadBodySchema,
  presignUploadResponseSchema,
  type DeviceRegistration,
  type PresignDownloadQuery,
  type PresignDownloadResponse,
  type PresignUploadBody,
  type PresignUploadResponse,
  type RegisterDeviceBody,
} from './media.js';

export { timeZoneSchema, type TimeZone } from './time.js';
export { fanoutJobSchema, type FanoutJob } from './fanout.js';
